### ISSUE TITLE
Ability to set max width of Content Card

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#43]
I tried this across some themes and some of them have very large columns, which means the content gets stretched to 1000px or more.

If we have an option for the max width of the content card and then center it, we would be able to let the user decide.

**Comment by khromov** [comment]
This could also be done in pure CSS, that'd probably be easier.

**Comment by ideag** [comment]
@khromov I think this is definitely a task for skin CSS file.

**Comment by ideag** [comment]
how wide should max-width be @khromov ? `600px` ? More? Less?

**Comment by khromov** [comment]
@ideag 600px sounds about right. Maybe also center it in the content?

``` css
.content_cards_card {
    max-width: 600px;
    margin-left: auto;
    margin-right: auto;
}
```
